config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'main#index'
  post 'create', to: 'main#create_tweet', as: 'create_tweet'
  post 'like/:tweet', to: 'main#like_tweet', as: 'like_tweet'
  post 'follow/:friend', to: 'main#follow', as: 'follow_user'
  post 'unfollow/:friend', to: 'main#unfollow', as: 'unfollow_user'
  post 'unlike/:tweet', to: 'main#unlike_tweet', as: 'unlike_tweet'
  post 'retweet/:tweet', to: 'main#retweet', as: 'retweet'
  get 'show/:tweet', to: 'main#show', as: 'show'
  get 'user/:user', to: 'main#userprofile', as: 'userprofile'
  get 'tweets/:user', to: 'main#usertweets', as: 'usertweets'
  get 'mytweets', to: 'main#mytweets'
  get 'myprofile', to: 'main#myprofile'
  get 'followers', to: 'main#listfollower'
  get 'following', to: 'main#listfollowing'
  get 'search', to: 'main#search', as: 'search'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id', class_name: 'User'
  belongs_to :friend, foreign_key: 'friend_id', class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :original, class_name: 'Tweet', foreign_key: 'tweet_id', optional: true
  has_many :likes
  paginates_per 50

  validates_presence_of :content

  scope :tweets_for_me, ->(friends_ids) { where(user_id: friends_ids) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates_presence_of :profile_img_url, :username

  has_many :tweets
  has_many :likes

  has_and_belongs_to_many   :friends,
                            class_name: 'User',
                            join_table: 'friends',
                            foreign_key: 'user_id',
                            association_foreign_key: 'friend_id'

  protected

  def serializable_hash(options = nil)
    super(options).merge(profile_img_url: profile_img_url, username: username)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_params, if: :devise_controller?
    
    protected
  
  def configure_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_img_url, :username])
  end
end
  

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :verify_authenticity_token, :except => [:index, :like_tweet]
  def index
    if user_signed_in?
      @tweets = Tweet.tweets_for_me(current_user.friends.pluck(:friend_id)).order(created_at: 'desc').page(params[:page])
      @tweets = Tweet.order(created_at: 'desc').page(params[:page])
    else
      @tweets = Tweet.order(created_at: 'desc').page(params[:page])
    end
    @user_likes = Like.where(user_id: current_user.id).pluck(:tweet_id) rescue []
    @user_friend = Friend.where(user_id: current_user.id).pluck(:friend_id) rescue []
  end

  def show
    @tweet = Tweet.find(params[:tweet])
    @user_likes = Like.where(user_id: current_user.id).pluck(:tweet_id) rescue []
  end

  def all_tweets
    @tweets = Tweet.order(created_at: 'desc').page(params[:page])
    @user_likes = Like.where(user_id: current_user.id).pluck(:tweet_id) rescue []
  end

  def create_tweet
    logger.info(@user_likes)
    @tweet = Tweet.new
    @tweet.content = params[:content]
    @tweet.user = current_user
    if @tweet.save
      flash[:notice] = 'Tweet sent!'
      redirect_to :root
    else
      @tweets = Tweet.order(created_at: 'desc').page(params[:page])
      flash[:alert] = 'Content is mandatory'
      render :index
    end
  end

  def like_tweet
    @tweet = Tweet.find(params[:tweet])
    @like = Like.new
    @like.tweet = @tweet
    @like.user = current_user
    @like.save
    if @like.save
      flash[:notice] = "Tweet liked!"
      if user_signed_in?
        @tweets = Tweet.tweets_for_me(current_user.friends.pluck(:friend_id)).order(created_at: 'desc').page(params[:page])
        @tweets = Tweet.order(created_at: 'desc').page(params[:page])
      else
        @tweets = Tweet.order(created_at: 'desc').page(params[:page])
      end
      @user_likes = Like.where(user_id: current_user.id).pluck(:tweet_id) rescue []
      @user_friend = Friend.where(user_id: current_user.id).pluck(:friend_id) rescue []
      respond_to do |format|
        format.js { render json: render_to_string('_tweets'), status: :created }
        # render json: { html: render_to_string(partial: 'random') }
      end
    else
    end
    # redirect_to :root
  end

  def unlike_tweet
    @like = Like.where(user_id: current_user.id).where(tweet_id: params[:tweet]).first
    @like.destroy
    flash[:notice] = "Tweet unliked!"
    redirect_to :root
  end

  def retweet
    @original = Tweet.find(params[:tweet])
    @tweet = Tweet.new
    @tweet.content = @original.content
    @tweet.user = current_user
    @tweet.tweet_id = @original.id
    @tweet.save
    @original.retweets = @original.retweets + 1
    @original.save
    flash[:notice] = 'Tweet retweeted!'
    redirect_to :root
  end

  def search
    @tweets = Tweet.where('content like :q', q: "%#{params[:q]}%").page(params[:page])
    @user_likes = Like.where(user_id: current_user.id).pluck(:tweet_id) rescue []
  end

  def mytweets
    @tweets = Tweet.where(user_id: current_user.id).page(params[:page])
    @user_likes = Like.where(user_id: current_user.id).pluck(:tweet_id) rescue []
  end

  def myprofile
    @tweets = Tweet.where(user_id: current_user.id).page(params[:page])
    @following = Friend.where(user_id: current_user.id).page(params[:page])
    @follower = Friend.where(friend_id: current_user.id).page(params[:page])
  end

  def follow
    @follow = Friend.new
    @follow.user = current_user
    @follow.friend = User.find(params[:friend])
    if @follow.save
      flash[:notice] = "Follow Successfully..."
      redirect_back fallback_location: root_path
    end
  end

  def unfollow
    @follow = Friend.where(user_id: current_user.id).where(friend_id: params[:friend]).first
    
    if @follow.destroy
      flash[:notice] = "Unfollow Successfully..."
      redirect_back fallback_location: root_path
    end
  end

  def listfollower
    @friends = Friend.where(friend_id: current_user.id).page(params[:page])
  end

  def listfollowing
    @friends = Friend.where(user_id: current_user.id).page(params[:page])
  end

  def userprofile
    @user = User.find(params[:user])
    @tweets = Tweet.where(user_id: @user.id).page(params[:page])
    @following = Friend.where(user_id: @user.id).page(params[:page])
    @follower = Friend.where(friend_id: @user.id).page(params[:page])
  end

  def usertweets
    @user = User.find(params[:user])
    @tweets = Tweet.where(user_id: @user.id).page(params[:page])
    @user_likes = Like.where(user_id: @user.id).pluck(:tweet_id) rescue []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_login_bar.html.erb
<div class="text-right">
  <% if user_signed_in? %>
    <%= link_to 'My Tweets', mytweets_path %> | <%= current_user.email %> | <%= link_to "Logout", destroy_user_session_path, { method: :delete } %> | <%= link_to 'Index', root_path %> | <%= link_to 'Following', following_path %> | <%= link_to 'Who follows me', followers_path %>
  <% else %>
    <%= link_to 'Login', new_user_session_path %> |
    <%= link_to 'Sign up', new_user_registration_path %> |
    <%= link_to 'Index', root_path %>
  <% end %>
</div>
<div class="text-right">
  <%= form_tag search_path, method: :get do %>
  <%= search_field_tag :q, params[:q] %>
  <%= submit_tag 'Search' %>
  <% end %>
</div>
<% if user_signed_in? %>
<h1>My Own Twitter - Welcome <%= link_to current_user.username, myprofile_path %> <%= image_tag current_user.profile_img_url, class: 'user-thumb', size: '50x50' %></h1>
<% else %>
<h1>My Own Twitter</h1>
<h5>Please SIGN-UP and then LOGIN if you want to get more functions</h5>
<% end %>
<hr>

<% if user_signed_in? %>
<h4>Write a tweet</h4>
<%= form_tag create_tweet_path, method: :post do %>
<%= text_area_tag 'content' %>
<%= submit_tag 'Submit' %>
<% end %>
<hr>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>My Own Twitter</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>
        <!-- Bootstrap -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        <!-- End Bootstrap -->
        <%= stylesheet_link_tag 'application', media: 'all' %>
        <%= javascript_pack_tag 'application' %>
    </head>


    <body>
        <div class="container">
            <%= render 'layouts/login_bar' %>
			<div id="flash">
            <% if flash[:notice] %>
                <%= render partial: 'notice' %>
            <% end %>
			</div>
            <% if flash[:alert] %>
                <div class="alert alert-danger" role="alert">
                    <%= flash[:alert] %>
                </div>
            <% end %>
            <%= yield %>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
        <script>
            $(document).on('click', '.like-btn', function () {
                var url = $(this).attr('url');
                var id = $(this).attr('id');
                $.ajax({
                    url: url+'.js',
                    type: "POST",
                    data: {
                        id: id
                    },
                    processData: false,
					contentType: false,
                    success: function (data) {
                        $('#tweets').html(data);
						$("#flash").html('<%= j render partial: "main/notice" %>');
                        $('.alert-success').html('Tweet Liked')
                    }
                });
            });
        </script>
    </body>
</html>

app/views/main/_notice.html.erb
<div class="alert alert-success" role="alert">
    <%= notice %>
</div>

app/views/main/_tweets.js.erb
<% @tweets.each do |tweet| %>
		<div class="tweet" id="tweet-<%= tweet.id %>%">
			<p><%= image_tag tweet.user.profile_img_url, class: 'user-thumb', size: '200x200' %>
				<% if user_signed_in? %>
					<% if tweet.user == current_user %>
						<%= link_to tweet.user.username, myprofile_path %>
					<% else %>
						<%= link_to tweet.user.username, userprofile_path(user: tweet.user) %>
					<% end %>
				<% else %>
					<%= tweet.user.username %>
				<% end %>
			</p>
			<div class="content">
				<% if user_signed_in? %>
					<%= raw tweet.content.split(' ').map{|c| c.index('#') === 0 ? (link_to c, search_url(q: c)) : c}.join(' ') %>
				<% else %>
					<%= raw tweet.content.split(' ').map{|c| c.index('#') === 0 ? c : c}.join(' ') %>
				<% end %>
			</div>
			<% if user_signed_in? %>
				<% if !tweet.original.nil? %>
					<p>
						<em><%= link_to 'See Original Tweet', show_path(tweet: tweet.original.id)%></em>
					</p>
				<% end %>
			<% else %>
				<p>
					<em><%= 'See Original Tweet'%></em>
				</p>
			<% end %>
			<% if user_signed_in? %>
				<p>
					<% if @user_likes.include? tweet.id %>
						<%= link_to 'Unike', unlike_tweet_path(tweet: tweet.id), method: :post, remote: true %>
					<% else %>
						<%# <%= link_to 'Like', like_tweet_path(tweet: tweet.id), class: 'like-btn', remote: true, method: :post %> 
						<a url="<%= like_tweet_path(tweet: tweet.id) %>" class="like-btn" id="<%= tweet.id %>">Like</a>
					<% end %>
					|
					<%= link_to 'Retweet', retweet_path(tweet: tweet.id), method: :post %>
					<% if @user_friend.include? tweet.user.id %>
					<%= link_to 'Unfollow', unfollow_user_path(friend: tweet.user.id), method: :post %>
					<% elsif tweet.user == current_user %>
					<% else %>
						|
						<%= link_to 'Follow', follow_user_path(friend: tweet.user.id), method: :post %>
					<% end %>
				</p>
			<% end %>
			<% if user_signed_in? %>
				<p><%= link_to (time_ago_in_words tweet.created_at), show_path(tweet: tweet.id) %>
					|
					<strong>Likes:</strong>
					<%= tweet.likes.count %>
					|
					<strong>Retweets:</strong>
					<%= tweet.retweets.blank? ? 0 : tweet.retweets %></p>
			<% else %>
				<p><%= time_ago_in_words tweet.created_at %>
					|
					<strong>Likes:</strong>
					<%= tweet.likes.count %>
					|
					<strong>Retweets:</strong>
					<%= tweet.retweets.blank? ? 0 : tweet.retweets %></p>
			<% end %>
		</div>
		<hr>
	<% end %>
	<%= paginate @tweets %>

app/views/main/all_tweets.html.erb
<% if @tweets.count > 0 %>

<% @tweets.each do |tweet| %>
<div class="tweet" id="tweet-<%= tweet.id %>%">
  <p><%= image_tag tweet.user.profile_img_url, class: 'user-thumb' %> <%= tweet.user.email %></p>
  <div class="content">
    <%= raw tweet.content.split(' ').map{|c| c.index('#') === 0 ? (link_to c, search_url(q: c)) : c}.join(' ') %>
  </div>
  <% if !tweet.original.nil? %>
    <p><em><%= link_to 'See original tweet', show_path(tweet: tweet.original.id)%></em></p>
  <% end %>
  <% if user_signed_in? %>
  <p>
    <% if @user_likes.include? tweet.id %>
    <%= link_to 'Unike', unlike_tweet_path(tweet: tweet.id), method: :post %>
    <% else %>
    <%= link_to 'Like', like_tweet_path(tweet: tweet.id), method: :post, remote: true %>
    <% end %> |
    <%= link_to 'Retweet', retweet_path(tweet: tweet.id), method: :post %>
  </p>
  <% end %>
  <p><%= link_to (time_ago_in_words tweet.created_at), show_path(tweet: tweet.id) %> | <strong>Likes:</strong> <%= tweet.likes.count %> | <strong>Retweets:</strong> <%= tweet.retweets.blank? ? 0 : tweet.retweets %></p>
</div>
<hr>
<% end %>
<%= paginate @tweets %>

<% else %>
<p><em>No tweets</em></p>
<% end %>

app/views/main/index.html.erb
<div class="block text-center col-12">
    <h1 class="block-title">Index</h1>
</div>
<hr>
<% if @tweets.count > 0 %>
	<div id="tweets">
	<%= render partial: 'main/tweets', locals: { items: @items},:formats=>[:js] %>
	</div>
<% else %>
	<p>
		<em>No tweets</em>
	</p>
<% end %>

app/views/main/listfollower.html.erb
<div class="block text-center col-12">
  <h1 class="block-title">Who Follows Me</h1>
</div>
<hr>
<% if @friends.count > 0 %>

<% @friends.each do |friend| %>
<div><p><%= image_tag friend.user.profile_img_url, class: 'user-thumb', size: '200x200' %> <%= link_to friend.user.username, userprofile_path(user: friend.user) %> </p></div>
<hr>
<% end %>
<%= paginate @friends %>

<% else %>
<p><em>No Followers</em></p>
<% end %>

app/views/main/listfollowing.html.erb
<div class="block text-center col-12">
  <h1 class="block-title">Following</h1>
</div>
<hr>
<% if @friends.count > 0 %>

<% @friends.each do |friend| %>
<div><p><%= image_tag friend.friend.profile_img_url, class: 'user-thumb', size: '200x200' %> <%= link_to friend.friend.username, userprofile_path(user: friend.friend) %> | <%= link_to 'Unfollow', unfollow_user_path(friend: friend.friend.id), method: :post %> </p></div>
<hr>
<% end %>
<%= paginate @friends %>

<% else %>
<p><em>Not following anybody</em></p>
<% end %>

app/views/main/myprofile.html.erb
<div class="block text-center col-12">
  <h1 class="block-title">My Profile Page</h1>
</div>
<hr>
<p>Username: <%= current_user.username %></p>
<p>Registration date: <%= current_user.created_at.time.to_date %></p>
<p>Tweets: <%= @tweets.count %></p>
<p>Number of people following: <%= @following.count %></p>
<p>Quantity of Followers: <%= @follower.count %></p>
<p>Tweets content: <%= link_to 'See All Tweets', mytweets_path %></p>
<p>Image:</p>
<p><%= image_tag current_user.profile_img_url, class: 'user-thumb', size: '200x200' %></p>

app/views/main/mytweets.html.erb
<div class="block text-center col-12">
  <h1 class="block-title">My Profile Page</h1>
</div>
<hr>
<% if @tweets.count > 0 %>

<% @tweets.each do |tweet| %>

<div class="tweet" id="tweet-<%= tweet.id %>%">
  <p><%= image_tag tweet.user.profile_img_url, class: 'user-thumb', size: '200x200' %> <%= link_to tweet.user.username, myprofile_path %></p>
  <div class="content">
    <%= raw tweet.content.split(' ').map{|c| c.index('#') === 0 ? (link_to c, search_url(q: c)) : c}.join(' ') %>
  </div>
  <% if !tweet.original.nil? %>
    <p><em><%= link_to 'See Original Tweet', show_path(tweet: tweet.original.id)%></em></p>
  <% end %>
  <% if user_signed_in? %>
  <p>
    <% if @user_likes.include? tweet.id %>
    <%= link_to 'Unike', unlike_tweet_path(tweet: tweet.id), method: :post %>
    <% else %>
    <%= link_to 'Like', like_tweet_path(tweet: tweet.id), method: :post, remote: true %>
    <% end %> |
    <%= link_to 'Retweet', retweet_path(tweet: tweet.id), method: :post %>
  </p>
  <% end %>
  <p><%= link_to (time_ago_in_words tweet.created_at), show_path(tweet: tweet.id) %> | <strong>Likes:</strong> <%= tweet.likes.count %> | <strong>Retweets:</strong> <%= tweet.retweets.blank? ? 0 : tweet.retweets %></p>
</div>
<hr>
<% end %>
<%= paginate @tweets %>

<% else %>
<p><em>No tweets</em></p>
<% end %>

app/views/main/search.html.erb
<div class="block text-center col-12">
  <h1 class="block-title">My Own Twitter- Search "<%= params[:q] %>"</h1>
</div>
<hr>
<% if @tweets.count > 0 %>

<% @tweets.each do |tweet| %>
<div class="tweet" id="tweet-<%= tweet.id %>%">
  <p><%= image_tag tweet.user.profile_img_url, class: 'user-thumb', size: '200x200' %>
    <% if user_signed_in? %>
    <% if tweet.user == current_user %>
    <%= link_to tweet.user.username, myprofile_path %>
    <% else %>
    <%= link_to tweet.user.username, userprofile_path(user: tweet.user) %>
    <% end %>
    <% else %>
    <%= tweet.user.username %>
    <% end %>
  </p>
  <div class="content">
    <%= tweet.content %>
  </div>
  <% if user_signed_in? %>
  <% if !tweet.original.nil? %>
    <p><em><%= link_to 'See Original Tweet', show_path(tweet: tweet.original.id)%></em></p>
  <% end %>
  <% else %>
    <p><em><%= 'See Original Tweet'%></em></p>
  <% end %>
  <% if user_signed_in? %>
  <p>
    <% if @user_likes.include? tweet.id %>
    <%= link_to 'Unike', unlike_tweet_path(tweet: tweet.id), method: :post %>
    <% else %>
    <%= link_to 'Like', like_tweet_path(tweet: tweet.id), method: :post, remote: true %>
    <% end %> |
    <%= link_to 'Retweet', retweet_path(tweet: tweet.id), method: :post %>
  </p>
  <% end %>
  <% if user_signed_in? %>
  <p><%= link_to (time_ago_in_words tweet.created_at), show_path(tweet: tweet.id) %> | <strong>Likes:</strong> <%= tweet.likes.count %> | <strong>Retweets:</strong> <%= tweet.retweets.blank? ? 0 : tweet.retweets %></p>
  <% else %>
  <p><%= time_ago_in_words tweet.created_at %> | <strong>Likes:</strong> <%= tweet.likes.count %> | <strong>Retweets:</strong> <%= tweet.retweets.blank? ? 0 : tweet.retweets %></p>
  <% end %>
</div>
<hr>
<% end %>
<%= paginate @tweets %>

<% else %>
<p><em>No tweets</em></p>
<% end %>

app/views/main/show.html.erb
<div class="block text-center col-12">
  <h1 class="block-title">Tweet - <%= @tweet.user.username %></h1>
</div>
<hr>
<div class="tweet" id="tweet-<%= @tweet.id %>%">
  <p><%= image_tag @tweet.user.profile_img_url, class: 'user-thumb', size: '200x200' %> 
  
    <% if @tweet.user == current_user %>
      <%= link_to @tweet.user.username, myprofile_path %>
    <% else %>
      <%= link_to @tweet.user.username, userprofile_path(user: @tweet.user) %>
    <% end %>
  </p>
  <div class="content">
    <%= @tweet.content %>
  </div>
  <% if !@tweet.original.nil? %>
    <p><em><%= link_to 'See Original Tweet', show_path(tweet: @tweet.id)%></em></p>
  <% end %>
  <p><%= time_ago_in_words @tweet.created_at %> | <strong>Likes:</strong> <%= @tweet.likes.count %> | <strong>Retweets:</strong> <%= @tweet.retweets.blank? ? 0 : @tweet.retweets %></p>
  <div class="likes">
    <% @tweet.likes.each do |like| %>
    <%= image_tag like.user.profile_img_url, class: 'small-list', size: '200x200', title: like.user.email %>
    <% end %>
  </div>
</div>
<hr>
<%= link_to '< Back', 'javascript:history.go(-1)' %>

app/views/main/userprofile.html.erb
<div class="block text-center col-12">
  <h1 class="block-title">Profile - <%= @user.username %></h1>
</div>
<hr>
<p>Username: <%= @user.username %></p>
<p>Registration date: <%= @user.created_at.time.to_date %></p>
<p>Tweets: <%= @tweets.count %></p>
<p>Number of people following: <%= @following.count %></p>
<p>Quantity of Followers: <%= @follower.count %></p>
<p>Tweets content: <%= link_to 'See All Tweets', usertweets_path(user: @user) %></p>
<p>Image:</p>
<p><%= image_tag @user.profile_img_url, class: 'user-thumb', size: '200x200' %></p>

app/views/main/usertweets.html.erb
<div class="block text-center col-12">
  <h1 class="block-title">Tweets - <%= @user.username %></h1>
</div>
<hr>
<% if @tweets.count > 0 %>

<% @tweets.each do |tweet| %>

<div class="tweet" id="tweet-<%= tweet.id %>%">
  <p><%= image_tag tweet.user.profile_img_url, class: 'user-thumb', size: '200x200' %> <%= link_to tweet.user.username, userprofile_path(user: tweet.user) %></p>
  <div class="content">
    <%= raw tweet.content.split(' ').map{|c| c.index('#') === 0 ? (link_to c, search_url(q: c)) : c}.join(' ') %>
  </div>
  <% if !tweet.original.nil? %>
    <p><em><%= link_to 'See original tweet', show_path(tweet: tweet.original.id)%></em></p>
  <% end %>
  <% if user_signed_in? %>
  <p>
    <% if @user_likes.include? tweet.id %>
    <%= link_to 'Unike', unlike_tweet_path(tweet: tweet.id), method: :post %>
    <% else %>
    <%= link_to 'Like', like_tweet_path(tweet: tweet.id), method: :post, remote: true %>
    <% end %> |
    <%= link_to 'Retweet', retweet_path(tweet: tweet.id), method: :post %>
  </p>
  <% end %>
  <p><%= link_to (time_ago_in_words tweet.created_at), show_path(tweet: tweet.id) %> | <strong>Likes:</strong> <%= tweet.likes.count %> | <strong>Retweets:</strong> <%= tweet.retweets.blank? ? 0 : tweet.retweets %></p>
</div>
<hr>
<% end %>
<%= paginate @tweets %>

<% else %>
<p><em>No tweets</em></p>
<% end %>